name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        name: Install Python 3.8
        with:
          python-version: '3.8'
      - name: Install tox
        run: python -m pip install tox
      - name: run test
        run: tox -e py38

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        name: Install Python 3.8
        with:
          python-version: '3.8'
      - name: Install pre commit
        run: python -m pip install pre-commit
      - name: run pre-commit
        run: pre-commit run --all --show-diff-on-failure

  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        name: Install Python 3.8
        with:
          python-version: '3.8'
      - name: Install dependecies
        run: python -m pip install wheel "setuptools_scm[toml]>=3.4"
      - name: create wheel
        run: python setup.py bdist_wheel
      - name: create source dist
        run: python setup.py sdist
      - name: Upload source bundle
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
